# GitHub Labeler Configuration
# Automatically labels PRs based on file paths
# See: https://github.com/actions/labeler

# API/Backend changes
api:
  - changed-files:
      - any-glob-to-any-file: '**/api/**'
      - any-glob-to-any-file: '**/src/api/**'

# Core platform code
platform:
  - changed-files:
      - any-glob-to-any-file: '**/src/platform.ts'
      - any-glob-to-any-file: '**/src/index.ts'

# Accessory/Device code
accessory:
  - changed-files:
      - any-glob-to-any-file: '**/src/thermostatAccessory.ts'
      - any-glob-to-any-file: '**/src/*Accessory.ts'

# TypeScript source files
typescript:
  - changed-files:
      - any-glob-to-any-file: '**/*.ts'
      - any-glob-to-any-file: '**/tsconfig.json'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: '**/docs/**'
      - any-glob-to-any-file: '**/README*'
      - any-glob-to-any-file: '**/CHANGELOG*'

# Test files
tests:
  - changed-files:
      - any-glob-to-any-file: '**/*.test.*'
      - any-glob-to-any-file: '**/*.spec.*'
      - any-glob-to-any-file: '**/test/**'
      - any-glob-to-any-file: '**/tests/**'
      - any-glob-to-any-file: '**/test-*.js'

# Configuration files
config:
  - changed-files:
      - any-glob-to-any-file: '**/*.yaml'
      - any-glob-to-any-file: '**/*.yml'
      - any-glob-to-any-file: '**/config.schema.json'
      - any-glob-to-any-file: '**/tsconfig.json'
      - any-glob-to-any-file: '**/.eslintrc*'
      - any-glob-to-any-file: '**/.prettierrc*'
      - any-glob-to-any-file: '**/.github/**'

# CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file: '**/.github/workflows/**'
      - any-glob-to-any-file: '**/.github/actions/**'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/package.json'
      - any-glob-to-any-file: '**/package-lock.json'

