# GitHub Labeler Configuration
# Automatically labels PRs based on file paths
# See: https://github.com/actions/labeler

# Frontend/UI changes
frontend:
  - changed-files:
      - any-glob-to-any-file: '**/frontend/**'
      - any-glob-to-any-file: '**/ui/**'
      - any-glob-to-any-file: '**/components/**'
      - any-glob-to-any-file: '**/*.tsx'
      - any-glob-to-any-file: '**/*.jsx'
      - any-glob-to-any-file: '**/*.vue'
      - any-glob-to-any-file: '**/*.svelte'

# Backend/API changes
backend:
  - changed-files:
      - any-glob-to-any-file: '**/backend/**'
      - any-glob-to-any-file: '**/api/**'
      - any-glob-to-any-file: '**/server/**'
      - any-glob-to-any-file: '**/*.go'
      - any-glob-to-any-file: '**/*.py'
      - any-glob-to-any-file: '**/*.java'
      - any-glob-to-any-file: '**/*.rb'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: '**/docs/**'
      - any-glob-to-any-file: '**/README*'
      - any-glob-to-any-file: '**/CHANGELOG*'

# Test files
tests:
  - changed-files:
      - any-glob-to-any-file: '**/*_test.go'
      - any-glob-to-any-file: '**/*.test.*'
      - any-glob-to-any-file: '**/*.spec.*'
      - any-glob-to-any-file: '**/test/**'
      - any-glob-to-any-file: '**/tests/**'

# Configuration files
config:
  - changed-files:
      - any-glob-to-any-file: '**/*.yaml'
      - any-glob-to-any-file: '**/*.yml'
      - any-glob-to-any-file: '**/*.json'
      - any-glob-to-any-file: '**/*.toml'
      - any-glob-to-any-file: '**/.github/**'
      - any-glob-to-any-file: '**/Dockerfile*'
      - any-glob-to-any-file: '**/docker-compose*'

# CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file: '**/.github/workflows/**'
      - any-glob-to-any-file: '**/.github/actions/**'
      - any-glob-to-any-file: '**/.circleci/**'
      - any-glob-to-any-file: '**/.travis.yml'
      - any-glob-to-any-file: '**/.gitlab-ci.yml'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/go.mod'
      - any-glob-to-any-file: '**/go.sum'
      - any-glob-to-any-file: '**/package.json'
      - any-glob-to-any-file: '**/package-lock.json'
      - any-glob-to-any-file: '**/requirements.txt'
      - any-glob-to-any-file: '**/Pipfile'
      - any-glob-to-any-file: '**/poetry.lock'
      - any-glob-to-any-file: '**/Cargo.toml'
      - any-glob-to-any-file: '**/Cargo.lock'

